### ISSUE TITLE
1,970 Gold Pulled After Abort

### ISSUE THREAD

**Issue by Alium58** [Kasekopf/loopsmol#13]
Most days loop smol aborts for me because I'm too low on meat. It is fixed when running again, because first thing it does is pull the gold.

Today 765 meat was spent on restoring MP and then abort due to running out of meat.
Next run it pulled the gold and spent 340 additional meat before continuing. For a total of 1,105 meat spent to restore my mp.

Currently the threshold is 200 meat to pull the gold. Perhaps adjust to 1,200? Or could get fancy and calculate how much meat is needed to restore MP using `Doc Galaktik's Invigorating Tonic` and set that as the limit. I'm sure there are many other approaches as well.

Desire is to pull the gold before causing an abort.

As an example, see line 51,658 for pulling the gold
[Alium_20240205 - Copy.txt](https://github.com/Kasekopf/loopsmol/files/14172292/Alium_20240205.-.Copy.txt)

**Comment by Kasekopf** [comment]
I changed around some of the pull logic so that it should immediately pull the gold when running out of meat while restoring MP (and then continue trying to restore MP). I wasn't able to test it since my runs don't normally need to pull gold, but let me know if that helps your issue!

**Comment by Alium58** [comment]
Whoa thanks for the quick update! Didn't get an abort yesterday. Which is abnormal and good. In run again now. Will update in a couple days. If no abort by then, I'd say this issue can be closed for sure.

**Comment by Alium58** [comment]
Closing, have had no issue with meat since this was merged. Thanks!
