### ISSUE TITLE
Easyfax missing important monster causing abort

### ISSUE THREAD

**Issue by VuvuzelaVirtuoso** [Kasekopf/loopsmol#14]
[VuvuzelaFeb6FailedFax.txt](https://github.com/Kasekopf/loopsmol/files/14189590/VuvuzelaFeb6FailedFax.txt)

This is the second time I've encountered this issue, and it seems to be due to Easyfax missing some monsters now. When Loopsmol starts trying to Fax a Camel Toe, it goes through the process of realizing that the fax has still not been delivered 6 times, then exits out with an error.

Looking in-game when this happens, I find that I have messages in in-game chat messages with EasyFax saying

> [16:35] [vuvuzela virtuoso](http://127.0.0.1:60080/showplayer.php?who=1014107): Camel's Toe
>[21:58] [Easyfax](http://127.0.0.1:60080/showplayer.php?who=2504737): I couldn't find that monster. Please look here [[link]](http://sourceforge.net/p/easyfax/code/HEAD/tree/list) http:// sourceforge.net/p/ easyfax/code/HEAD/ tree/list for a list of monster names.

I am able to manually intervene once things error out, and request a fax from OnlyFax instead, then rerun and all works fine.

I know that there is already a boolean option to utilize Faxbots or not, but obviously it would be ideal to be able to still make use of a fax, so it would be nice if either Onlyfax could be given request priority, and/or if after a couple failures, that the loop script would try an alternate faxbot instead.

**Comment by libraryaddict** [comment]
#15

**Comment by VuvuzelaVirtuoso** [comment]
Thank you! I am no longer experiencing the issue.
