### ISSUE TITLE
Improve Monstrous Boiler Combat

### ISSUE THREAD

**Issue by Alium58** [Kasekopf/loopsmol#26]
Issue - beaten up by monstrous boiler.

Details - Was running 87 ML. Equipped seal clubbing club to be ready to banish, if needed. Used sauce storm (which did little damage) until out of MP. Then attacked multiple rounds for 1 damage each.

[alium_20240329.txt](https://github.com/Kasekopf/loopsmol/files/14804157/alium_20240329.txt)

**Comment by Kasekopf** [comment]
It looks like this was maybe fixed in #24, please reopen if this happens again.
