### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by PKPenguin321** [Kasekopf/loopsmol#30]
Upon starting a shrunken adventurer run and running the script, you get:
`Script exception: Function 'to_location( )' undefined. This script may require a more recent version of KoLmafia and/or its supporting scripts. (.../KoLmafia/NEWMAF/scripts/loopsmol/loopsmol.js#9761)`

**Comment by Kasekopf** [comment]
Are you on the latest version of the script? I think this was fixed by #29.

**Comment by PKPenguin321** [comment]
Yeah seems it was failing to update, I had to delete and reinstall the project. Thanks
