### ISSUE TITLE
Beaten up by ghost

### ISSUE THREAD

**Issue by Alium58** [Kasekopf/loopsmol#4]
Dusken Raider got me when I had +56ML. Looks like I simply attacked each turn.

Didn't have cleaver equipped so wasn't doing much elemental damage
![image](https://github.com/Kasekopf/loopsmol/assets/4781473/a39750c0-25aa-4f57-978b-be4cd41656b7)

Here's the full log
[Alium_20231122.txt](https://github.com/Kasekopf/loopsmol/files/13445421/Alium_20231122.txt)

**Comment by Kasekopf** [comment]
Thanks, I removed some macro code leftover from gyou. Should be fixed now, but please reopen if it keeps happening.
