### ISSUE TITLE
Need club in main hand for batter up

### ISSUE THREAD

**Issue by Alium58** [Kasekopf/loopsmol#5]
Combat aborted since batter up couldn't be used. Per wiki, club has to be in main hand

![image](https://github.com/Kasekopf/loopsmol/assets/4781473/f9aacb85-865f-4b72-ade2-207fa798fd02)
![image](https://github.com/Kasekopf/loopsmol/assets/4781473/ce00b023-aa38-451b-901a-eecbabf0ef28)

![image](https://github.com/Kasekopf/loopsmol/assets/4781473/657dbb57-47ab-4e87-aa16-12d2f936a2c6)
https://kol.coldfront.net/thekolwiki/index.php/Batter_Up!_(skill)

![image](https://github.com/Kasekopf/loopsmol/assets/4781473/15be7cd8-5b12-4716-ad99-de1b0578523f)

**Comment by Kasekopf** [comment]
Thanks for the report, this should be fixed in the newest version. Please reopen if it keeps happening.
