### ISSUE TITLE
Beaten up at Ice Peak

### ISSUE THREAD

**Issue by cfstoecker** [Kasekopf/loopsmol#6]
I got beaten up at Icy Peak doing Ghostly Memories.  This happened for me in the 1st and 3rd run of the script (but not the 2nd).  Here is the equipment I had:

Hat:		nurse's hat (Power: 200) [unequip]		
Back:		protonic accelerator pack [unequip]		
Shirt:		sea salt scrubs (Power: 200) [unequip]		
Weapon:		Fourth of May Cosplay Saber (Damage: 10 - 20, 1h) [unequip]	[upgrade] 
Off-Hand:		carnivorous potted plant [unequip]		
Pants:		bloodied surgical dungarees (Power: 155) [unequip]		
Accessory 1:		your cowboy boots [unequip]		
Accessory 2:		mafia thumb ring [unequip]		
Accessory 3:		Lil' Doctor™ bag [unequip]		
Familiar:		LED candle [unequip]

And here's the log:

Executing Crypt/Nook Eye [Route]

Executing Crypt/Nook Eye
Reconfiguring retro cape
Preference retroCapeWashingInstructions changed from kill to hold
Preference _concoctionDatabaseRefreshes changed from 1730 to 1731
Preference _concoctionDatabaseRefreshes changed from 1731 to 1732
CCS set to grimoire_macro
Preference _concoctionDatabaseRefreshes changed from 1732 to 1733
Autoattack is disabled.
Using 2 evil eye...
Preference cyrptNookEvilness changed from 18 to 12
Preference cyrptTotalEvilness changed from 44 to 38
Preference _concoctionDatabaseRefreshes changed from 1733 to 1734
Finished using 2 evil eye.
Crypt/Nook Eye completed!
Preference _concoctionDatabaseRefreshes changed from 1734 to 1735

Executing Orc Chasm/ABoo Clues [Route]

Executing Orc Chasm/ABoo Clues
Putting on nurse's hat...
Preference _concoctionDatabaseRefreshes changed from 1735 to 1736
Equipment changed.
Putting on protonic accelerator pack...
Preference _concoctionDatabaseRefreshes changed from 1736 to 1737
Equipment changed.
Maximizer: 0.01 MP regen, 0.001 HP regen, item, -"equip ¶10058", -acc2, -acc3, -back, -familiar, -hat, -off-hand, -shirt
Maximizing...
32 combinations checked, best score 676.50
Wielding Fourth of May Cosplay Saber...
Equipment changed.
Putting on bloodied surgical dungarees...
Equipment changed.
Putting on your cowboy boots...
Equipment changed.
Saving outfit: Script Outfit 3
Outfit saved
CCS set to grimoire_macro
Preference choiceAdventure611 changed from to 1
choiceAdventure1430 => 1
Preference choiceAdventure1430 changed from 0 to 1

Preference nextAdventure changed from The Defiled Nook to A-Boo Peak

Visit to Highlands: A-Boo Peak in progress...
Preference lastAdventure changed from The Defiled Nook to A-Boo Peak

[319] A-Boo Peak
Preference lastEncounter changed from No Nook Unknown to Ghostly Memories
Encounter: Ghostly Memories
Preference lastCartographyBooPeak changed from 300 to 301
Preference lastEncounter changed from Ghostly Memories to The Horror...
Encounter: The Horror...
Encounter: The Horror...
Preference booPeakProgress changed from 98 to 96
You lose 1 hit point
You lose 1 hit point
Encounter: The Horror...
Preference booPeakProgress changed from 96 to 92
You lose 3 hit points
You lose 4 hit points
Encounter: The Horror...
Preference booPeakProgress changed from 92 to 86
You lose 13 hit points
You lose 15 hit points
Encounter: The Horror...
Preference booPeakProgress changed from 86 to 78
You lose 34 hit points
You lose 37 hit points
Preference booPeakProgress changed from 78 to 76
You lose 67 hit points
You lose 75 hit points

Preference _concoctionDatabaseRefreshes changed from 1737 to 1738
Fight was lost (debug info: 0 => 3, (172 => 171); stop.
hpAutoRecoveryTarget => 0
Preference hpAutoRecoveryTarget changed from 0.0 to 0
mpAutoRecoveryTarget => 0
Preference mpAutoRecoveryTarget changed from 0.0 to 0
CCS set to grimoire_macro
mpAutoRecoveryItems => phonics down;knob goblin superseltzer;mountain stream soda;magical mystery juice;knob goblin seltzer;cherry cloaca cola;soda water;doc galaktik's invigorating tonic
Preference mpAutoRecoveryItems changed from phonics down;knob goblin superseltzer;mountain stream soda;magical mystery juice;knob goblin seltzer;cherry cloaca cola;soda water;doc galaktik's invigorating tonic;black cherry soda to phonics down;knob goblin superseltzer;mountain stream soda;magical mystery juice;knob goblin seltzer;cherry cloaca cola;soda water;doc galaktik's invigorating tonic
hpAutoRecoveryItems => cannelloni cocoon;scroll of drastic healing;tongue of the walrus;lasagna bandages;doc galaktik's ailment ointment
Preference hpAutoRecoveryItems changed from cannelloni cocoon;scroll of drastic healing;tongue of the walrus;lasagna bandages;doc galaktik's ailment ointment;doc galaktik's homeopathic elixir;relaxing hot tub to cannelloni cocoon;scroll of drastic healing;tongue of the walrus;lasagna bandages;doc galaktik's ailment ointment
choiceAdventure1340 => 0
Preference choiceAdventure1340 changed from 3 to 0
choiceAdventure1341 => 0
Preference choiceAdventure1341 changed from 1 to 0
Preference choiceAdventure1414 changed from 2 to
choiceAdventure1494 => 0
Preference choiceAdventure1494 changed from 2 to 0
choiceAdventure1468 => 4
Preference choiceAdventure1468 changed from 1 to 4
choiceAdventure1470 => 4
Preference choiceAdventure1470 changed from 2 to 4
choiceAdventure1472 => 1
Preference choiceAdventure1472 changed from 2 to 1
choiceAdventure1473 => 1
Preference choiceAdventure1473 changed from 2 to 1
choiceAdventure502 => 0
Preference choiceAdventure502 changed from 2 to 0
choiceAdventure505 => 0
Preference choiceAdventure505 changed from 1 to 0
choiceAdventure1223 => 0
Preference choiceAdventure1223 changed from 1 to 0
choiceAdventure1224 => 0
Preference choiceAdventure1224 changed from 1 to 0
choiceAdventure1225 => 0
Preference choiceAdventure1225 changed from 1 to 0
choiceAdventure1226 => 0
Preference choiceAdventure1226 changed from 2 to 0
choiceAdventure1227 => 0
Preference choiceAdventure1227 changed from 1 to 0
choiceAdventure1228 => 0
Preference choiceAdventure1228 changed from 3 to 0
Preference choiceAdventure893 changed from 2 to
choiceAdventure155 => 4
Preference choiceAdventure155 changed from 5 to 4
choiceAdventure793 => 0
Preference choiceAdventure793 changed from 1 to 0
choiceAdventure139 => 1
Preference choiceAdventure139 changed from 3 to 1
choiceAdventure140 => 2
Preference choiceAdventure140 changed from 3 to 2
choiceAdventure141 => 1
Preference choiceAdventure141 changed from 3 to 1
choiceAdventure143 => 1
Preference choiceAdventure143 changed from 3 to 1
choiceAdventure144 => 1
Preference choiceAdventure144 changed from 3 to 1
choiceAdventure1433 => 0
Preference choiceAdventure1433 changed from 3 to 0
choiceAdventure923 => 0
Preference choiceAdventure923 changed from 1 to 0
choiceAdventure924 => 0
Preference choiceAdventure924 changed from 1 to 0
choiceAdventure928 => 0
Preference choiceAdventure928 changed from 4 to 0
choiceAdventure1018 => 0
Preference choiceAdventure1018 changed from 1 to 0
choiceAdventure1019 => 0
Preference choiceAdventure1019 changed from 1 to 0
choiceAdventure506 => 0
Preference choiceAdventure506 changed from 2 to 0
choiceAdventure507 => 0
Preference choiceAdventure507 changed from 1 to 0
choiceAdventure503 => 0
Preference choiceAdventure503 changed from 3 to 0
choiceAdventure504 => 0
Preference choiceAdventure504 changed from 3 to 0
choiceAdventure875 => 0
Preference choiceAdventure875 changed from 1 to 0
Preference choiceAdventure900 changed from 2 to
choiceAdventure1436 => 0
Preference choiceAdventure1436 changed from 1 to 0
choiceAdventure163 => 1
Preference choiceAdventure163 changed from 4 to 1
choiceAdventure888 => 3
Preference choiceAdventure888 changed from 5 to 3
choiceAdventure889 => 3
Preference choiceAdventure889 changed from 5 to 3
Preference choiceAdventure894 changed from 1 to
choiceAdventure118 => 2
Preference choiceAdventure118 changed from 1 to 2
Preference choiceAdventure1074 changed from 1 to
choiceAdventure579 => 0
Preference choiceAdventure579 changed from 2 to 0
choiceAdventure582 => 0
Preference choiceAdventure582 changed from 1 to 0
choiceAdventure787 => 0
Preference choiceAdventure787 changed from 2 to 0
choiceAdventure785 => 0
Preference choiceAdventure785 changed from 2 to 0
choiceAdventure783 => 0
Preference choiceAdventure783 changed from 2 to 0
choiceAdventure781 => 0
Preference choiceAdventure781 changed from 2 to 0
choiceAdventure876 => 0
Preference choiceAdventure876 changed from 1 to 0
choiceAdventure877 => 0
Preference choiceAdventure877 changed from 1 to 0
choiceAdventure878 => 0
Preference choiceAdventure878 changed from 4 to 0
choiceAdventure879 => 0
Preference choiceAdventure879 changed from 1 to 0
choiceAdventure880 => 0
Preference choiceAdventure880 changed from 1 to 0
Preference choiceAdventure897 changed from 2 to
choiceAdventure855 => 0
Preference choiceAdventure855 changed from 4 to 0
choiceAdventure856 => 0
Preference choiceAdventure856 changed from 1 to 0
choiceAdventure857 => 0
Preference choiceAdventure857 changed from 1 to 0
choiceAdventure858 => 0
Preference choiceAdventure858 changed from 1 to 0
choiceAdventure866 => 0
Preference choiceAdventure866 changed from 2 to 0
choiceAdventure1432 => 0
Preference choiceAdventure1432 changed from 1 to 0
choiceAdventure178 => 1
Preference choiceAdventure178 changed from 2 to 1
choiceAdventure788 => 0
Preference choiceAdventure788 changed from 1 to 0
choiceAdventure523 => 5
Preference choiceAdventure523 changed from 4 to 5
choiceAdventure105 => 3
Preference choiceAdventure105 changed from 1 to 3
Preference choiceAdventure892 changed from 1 to
choiceAdventure669 => 0
Preference choiceAdventure669 changed from 1 to 0
choiceAdventure670 => 0
Preference choiceAdventure670 changed from 4 to 0
choiceAdventure671 => 0
Preference choiceAdventure671 changed from 4 to 0
choiceAdventure672 => 0
Preference choiceAdventure672 changed from 3 to 0
choiceAdventure673 => 0
Preference choiceAdventure673 changed from 3 to 0
choiceAdventure674 => 0
Preference choiceAdventure674 changed from 3 to 0
choiceAdventure1026 => 0
Preference choiceAdventure1026 changed from 2 to 0
choiceAdventure675 => 0
Preference choiceAdventure675 changed from 4 to 0
choiceAdventure676 => 0
Preference choiceAdventure676 changed from 4 to 0
choiceAdventure677 => 0
Preference choiceAdventure677 changed from 1 to 0
choiceAdventure678 => 0
Preference choiceAdventure678 changed from 1 to 0
choiceAdventure1431 => 0
Preference choiceAdventure1431 changed from 4 to 0
choiceAdventure786 => 0
Preference choiceAdventure786 changed from 1 to 0
choiceAdventure784 => 0
Preference choiceAdventure784 changed from 1 to 0
choiceAdventure780 => 0
Preference choiceAdventure780 changed from 1 to 0
Preference choiceAdventure896 changed from 1 to
choiceAdventure90 => 2
Preference choiceAdventure90 changed from 3 to 2
Preference choiceAdventure901 changed from 2 to
Preference choiceAdventure891 changed from 2 to
Preference choiceAdventure902 changed from 2 to
choiceAdventure496 => 1
Preference choiceAdventure496 changed from 2 to 1
choiceAdventure513 => 1
Preference choiceAdventure513 changed from 2 to 1
choiceAdventure514 => 1
Preference choiceAdventure514 changed from 2 to 1
choiceAdventure515 => 1
Preference choiceAdventure515 changed from 2 to 1
choiceAdventure791 => 0
Preference choiceAdventure791 changed from 1 to 0
Preference choiceAdventure1498 changed from 1 to
Preference choiceAdventure611 changed from 1 to
choiceAdventure1430 => 0
Preference choiceAdventure1430 changed from 1 to 0
JavaScript exception: Fight was lost (debug info: 0 => 3, (172 => 171); stop. (file:/C:/kolmafia/scripts/loopsmol/loopsmol.js#11195)
at file:/C:/kolmafia/scripts/loopsmol/loopsmol.js:11195 (_do)
at file:/C:/kolmafia/scripts/loopsmol/loopsmol.js:5878 (execute)
at file:/C:/kolmafia/scripts/loopsmol/loopsmol.js:10860 (execute)
at file:/C:/kolmafia/scripts/loopsmol/loopsmol.js:5796 (run)
at file:/C:/kolmafia/scripts/loopsmol/loopsmol.js:19286 (main)
Loading character status...
Sending login request...
Ping test: average delay is 123.00 msecs.
Loading character status...
Requests complete.

**Comment by Kasekopf** [comment]
Thanks for the report! I thought I had fixed this before, but looking at the code the fix was broken. I added another fix to the newest version which might actually work this time; please let me know if it happens again with the newest version.
