### ISSUE TITLE
Feature Requests: Instant Karma, Cowboy Boots, Stillsuit

### ISSUE THREAD

**Issue by cfstoecker** [Kasekopf/loopsmol#7]
1. Could you make the script eat basic hotdogs until back to level 13 before doing the NS so we can pick up Instant Karma?
2. Could you have the script visit the L&T office at the start to pick up the cowboy boots?
3. Could you have the script put the stillsuit on a familiar that's unused at the start?  (I've found if I manually put it on a Cheshire Bat it stays there.)

**Comment by Kasekopf** [comment]
All three of these things should now be possible! For 1 you'll have to set the `delevel` arg. For 2, it should default to putting it on the cubeling, which you can change with the `stillsuit` arg. Please reopen if you notice one of them is not working.
