### ISSUE TITLE
loopsmol sim doesn't recognize a few things I have

### ISSUE THREAD

**Issue by cpenny86** [Kasekopf/loopsmol#8]
I haven't tried running the script yet and so I have no idea if this will translate to in-run issues, but when I ran sim it missed two things that I actually have: 

* CMC (currently installed in workshed space but no visits left, if that makes a difference for how the script finds it)
* Permanent +10 pool skill (I got this ages ago and can see it in my Quest Log under "other accomplishments")

I'm going to try it out shortly & will let you know if it runs into any visible hiccups because of this.

**Comment by cpenny86** [comment]
Update: I set my workshed to CMC using the prefs and it worked fine. I haven't checked my logs to see how it did in the billiards room but it got through that zone, anyway.

**Comment by Kasekopf** [comment]
Thanks, one of the CMC sim entries was supposed to be the model trainset; fixed.

For the pool skill, if you are sure you have the full +10 permanent pool skill, you can tell mafia with `set poolSharkCount=25`
