### ISSUE TITLE
Unable to find available task, but the run is not complete.

### ISSUE THREAD

**Issue by capncastom** [Kasekopf/loopsmol#9]
Hi!

Ive run into this javascript exception stoppage the past couple runs. Im L13, and this run thru it popped up right after opening FantasyRealm.

```
Executing Misc/Open Fantasy [Route]

Executing Misc/Open Fantasy
CCS set to grimoire_macro
Autoattack is disabled.
choiceAdventure1280 => 1
Preference choiceAdventure1280 changed from 0 to 1
Preference lastEncounter changed from The Knob Goblin King to Welcome to FantasyRealm
Encounter: Welcome to FantasyRealm
Preference _frHoursLeft changed from 0 to 5
Preference _frAreasUnlocked changed from to The Bandit Crossroads,
You acquire an item: FantasyRealm Warrior's Helm
You acquire an item: FantasyRealm G. E. M.
Misc/Open Fantasy completed!
Remaining tasks:
Misc/Acquire Birch Battery
Palindome/Copperhead
McLargeHuge/Clover Ore
McLargeHuge/Trapper Return
Palindome/Cold Snake
McLargeHuge/Ninja
McLargeHuge/Climb
Palindome/Protesters
McLargeHuge/Peak
McLargeHuge/Finish
Palindome/Protesters Finish
Palindome/Hot Snake Postcastle
Palindome/Hot Snake Precastle
Palindome/Sleaze Frat Snake
Palindome/Sleaze Star Snake
Palindome/Zepplin
Palindome/Spooky Snake Postcrypt
Palindome/Spooky Snake Precrypt
Palindome/Talisman
Palindome/Palindome Dog
Palindome/Palindome Dudes
Palindome/Palindome Photos
Palindome/Alarm Gem
Palindome/Palindome Nuts
Palindome/Open Alarm
Palindome/Boss
Macguffin/Open Pyramid
Macguffin/Upper Chamber
Macguffin/Middle Chamber
Macguffin/Middle Chamber Delay
Macguffin/Get Token
Macguffin/Get Bomb
Macguffin/Use Bomb
Macguffin/Boss
Macguffin/Finish
Wand/Plus Sign
Wand/Get Teleportitis
Keys/Daily Dungeon Candy Cane
Keys/All Heroes
Tower/Start
Tower/Cold Challenge
Tower/Hot Challenge
Tower/Mysticality Challenge
Tower/Muscle Challenge
Tower/Moxie Challenge
Tower/Speed Challenge
Tower/Spooky Challenge
Tower/Stench Challenge
Tower/Sleaze Challenge
Tower/Speed Boss
Tower/Stat Boss
Tower/Element Boss
Tower/Coronation
Tower/Frank
Tower/Maze
Tower/Digital Lock
Tower/Star Lock
Tower/Sneaky Pete Lock
Tower/Jarlsberg Lock
Tower/Boris Lock
Tower/Skeleton Lock
Tower/Door
Tower/Wall of Skin
Tower/Wall of Meat
Tower/Wall of Bones
Tower/Wand A
Tower/Wand N
Tower/Wand D
Tower/Wand Parts
Tower/Wand
Tower/Mirror
Tower/Shadow
Tower/Naughty Sorceress
Misc/Limit Stats
Misc/Swap Workshed
Misc/Autumnaton
Misc/Trainset
Misc/Cincho
Misc/Protonic Ghost
logPreferenceChange => false
Preference logPreferenceChange changed from true to false
logPreferenceChangeFilter =>
autoSatisfyWithMall => false
dontStopForCounters => false
hpAutoRecoveryTarget => 1
mpAutoRecoveryTarget => 0.3
choiceAdventureScript =>
autoTuxedo => false
allowNonMoodBurning => true
CCS set to grimoire_macro
choiceAdventure1106 => 1
choiceAdventure1340 => 1
choiceAdventure1468 => 2
choiceAdventure1469 => 1
choiceAdventure1470 => 3
choiceAdventure1471 => 2
choiceAdventure1472 => 1
choiceAdventure1474 => 3
choiceAdventure1475 => 3
stillsuitFamiliar =>
choiceAdventure105 => 3
choiceAdventure90 => 2
choiceAdventure788 => 0
choiceAdventure118 => 2
choiceAdventure786 => 0
choiceAdventure781 => 0
choiceAdventure783 => 0
choiceAdventure787 => 0
choiceAdventure785 => 0
choiceAdventure791 => 0
choiceAdventure1345 => 1
choiceAdventure155 => 4
choiceAdventure1430 => 0
choiceAdventure1280 => 0
JavaScript exception: Unable to find available task, but the run is not complete. (file:/Users/casey/Library/Application%20Support/KoLmafia/scripts/loopsmol/loopsmol.js#20027)
at file:/Users/casey/Library/Application%20Support/KoLmafia/scripts/loopsmol/loopsmol.js:20027 (main) 
```

not sure what is making it sad.
[capn_castom_20240107.txt](https://github.com/Kasekopf/loopsmol/files/13853871/capn_castom_20240107.txt)

thanks for another beautiful script, btw!

**Comment by Kasekopf** [comment]
Huh, it looks like it just never tried to get any ore for the L8 quest, which blocked the L8 quest and part of the L11 quest. Has it gotten ore for you in the past? How did it do it?

**Comment by capncastom** [comment]
Looking at session data, the runs it was able to clear the trapper by itself it got ore from Train set drops.
When I switched to starting with workshed = CMC / swapworkshed = train set , thats when ore needs were not met.

**Comment by capncastom** [comment]
tried running it again today after putting a Mountain Man in chateau painting. Still did not find a way to collect ore.

What methods does the script use for ore when not running the train?  I dont think Im missing anything that speeds that quest. . .

**Comment by Kasekopf** [comment]
Huh, it seems like the issue is that it's not actually picking up any extros from the CMC, so it never finishes that and switches to trainset. But it expects to get the ore from trainset eventually, so it doesn't try to use other resources.

I'm not sure why it's not picking up any extros. It could just be not enough fights in the right zone in a row, or a bug in the script.

**Comment by capncastom** [comment]
When I ran it again today, It picked up 4/5 Extros before it broke at the Trapper. After I fought the chateau painting an clovered the mine for 1 more ore, it ran fine. (with the exception of losing to the snojo with round time-outs from around free snowman 7 onward at the beginning of the day. But thats a whole dif thing.)

**Comment by Kasekopf** [comment]
Ok, so it is able to get extros sometimes, but not all of them reliably. I adjusted the ore plan so that it will use other resources for ore when you have CMC out, which should stop it from being blocked there. Maybe in the future I can try to improve the routing to grab extros more easily.

**Comment by capncastom** [comment]
thats awesome, thanks for the consideration!
